site_name: unobin AWS library
site_url: https://cloudboss.co/docs/unobin-library-aws/
repo_url: https://github.com/cloudboss/unobin-library-aws
repo_name: cloudboss/unobin-library-aws
copyright: Copyright (c) 2026 cloudboss

theme:
  name: cloudboss
  logo: assets/logo.svg
  favicon: assets/logo.svg

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

extra:
  google_analytics_property: G-MZGMN4NWS2
  unobin_reference: true
  version:
    provider: mike
    default: latest

nav:
  - AWS library: index.md
  - Reference: reference/
